#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="grapi"

mkdir -p "${CONFIG_PATH}"
configure_logging

print_debug "Configuring GRAPI"
configure_grapi
print_debug "Finished Configuring GRAPI"

liftoff
